name: kexp_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  kexp_api:
    path: ../lib/kexp_api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
