name: package kexp cli

on:
  workflow_dispatch:

jobs:
  create_cli_archive:
    name: create the cli archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.11
      
      - name: run cli tests to ensure quality
        run: |
          cd ./kexp-cli
          dart pub get
          cd ./lib/kexp_api
          dart test
          cd ${{ github.workspace }}

      - name: prune and archive cli from repo
        run: |
          mkdir working
          git archive --format tar.gz -v --worktree-attributes -o "./working/archive.tar.gz" HEAD kexp-cli

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive.tar.gz
          overwrite: true
          path: working
          
