name: package kexp cli

on:
  workflow_dispatch:

jobs:
  create_cli_archive:
    name: create the cli archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.11
      
      - name: run cli tests to ensure quality
        run: |
          cd ./kexp-cli
          dart pub get
          cd ./lib/kexp_api
          dart test
          cd ${{ github.workspace }}

#extract cli from repo


#prune cli 


#archive  cli
