name: package kexp cli

on:
  workflow_dispatch:

jobs:
  create_cli_archive:
    name: create the cli archive
    runs-on: ubuntu-latest
    outputs: 
      archive-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.11
      
      - name: run cli tests to ensure quality
        run: |
          cd ./kexp-cli
          dart pub get
          cd ./lib/kexp_api
          dart test
          cd ${{ github.workspace }}

      - name: prune and archive cli from repo
        run: |
          mkdir working
          git archive --format tar.gz -v --worktree-attributes -o "./working/archive.tar.gz" HEAD kexp-cli

      - name: upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: archive.tar.gz
          overwrite: true
          path: working
          
  update_readme:
    name: update the readme file with link to latest archive
    runs-on: ubuntu-latest
    needs: create_cli_archive
    env: 
      ARCH_URL: ${{needs.create_cli_archive.outputs.archive-url}}
    steps:
      - name: pull down repository
        uses: actions/checkout@v5
        with:
          token: ${{secrets.GHAKEY}}
      - name: update README.md
        run: |
          cd kexp-cli
          sed -i "s|\[Latest Artifact\](.*)|\[Latest Artifact\](${ARCH_URL})|" ./README.md
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "README update"
          git push --no-verify
